### ISSUE TITLE
USER STORY: As a site user I can create a profile so that i can login to the site 

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/PP4#1]
EPIC: User Profile Creation

As a **site user** I can **can create a profile** so that **i can login to the site**

**Acceptance criteria**

- [ ] - User registration form with email, username and password
- [ ] - Create unique username and choose a password
- [ ] - User is created in Django admin panel

**Tasks**

- [ ] Task 1: Design and implement a registration form
- [ ] Task 2: Add validation and error handling
- [ ] Task 3: Test functionality
